### ISSUE TITLE
Search only fields are not added to an upsert/add payload

### ISSUE THREAD

**Issue by iloveitaly** [NetSweet/netsuite#486]
@cgunther it looks like some of the search-only fields that were added are also non-search only fields (`other_ref_num`) is one example.

What do you think about checking if the field already exists within the `search_only_field` logic and not adding it if it's already been set as another field type?

**Comment by cgunther** [comment]
Whoops. When defining the initial list of `search_only_field`s, I manually compared the fields of `TransactionSearchRowBasic` to the fields of `Invoice` and skipped any that existed on the underlying `Invoice` record, but `other_ref_num` must have slipped by.

I opened #487 as a quick fix while we discuss a long term fix.

I had a hunch this might arise, but figured it'd be once a shared concept was extracted for `TransactionSearchRowBasic` that could be shared amongst multiple records (ie. `Invoice`, `CreditMemo`, etc.).

What you're describing could work, but then there's still an issue if `fields` happens to be called after `search_only_fields`, right? We'd maybe want to update the `field` logic too to error if you're passing a name that was already included as a `search_only_field`.

I wonder if part of the problem is that behind the scenes `search_only_field` also calls `field`. Maybe `field` needs to be split up between appending to the list of fields and defining the reader/writer methods, the latter of which likely being the only part `search_only_field` cares about.

Let me take a deeper look at the code and see where the list of fields is used, expecting to include both `read_only` and `search_only` and see if it'd make sense that `fields` only had the standard fields, not also including the `read_only` and `search_only` fields.

**Comment by iloveitaly** [comment]
@cgunther I think you are right—`field` should check and error out as well. I think it's worth putting an error check on both functions. 

Maybe we could do something generic across all field-related functions (`ensure_field_not_in_use!`) that checks across all field lists (including read-only fields).
